# Generated by Django 5.2 on 2025-05-07 16:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('lastname', models.CharField(max_length=32)),
                ('firstname', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=32)),
                ('street', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('plz', models.CharField(max_length=5)),
                ('comment', models.TextField(blank=True)),
                ('voucher', models.CharField(blank=True, max_length=32)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='alpacabooking.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='alpacabooking.eventtype'),
        ),
        migrations.CreateModel(
            name='ResourceCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacities', to='alpacabooking.eventtype')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alpacabooking.resourcetype')),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_types', to='alpacabooking.eventtype')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='alpacabooking.booking')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alpacabooking.tickettype')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alpacabooking.resourcetype')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='alpacabooking.tickettype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('start_time', 'event_type'), name='unique_start_time_event_type'),
        ),
        migrations.AddConstraint(
            model_name='resourcecapacity',
            constraint=models.UniqueConstraint(fields=('resource_type', 'event_type'), name='unique_resource_type_event_type'),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.UniqueConstraint(fields=('name', 'event_type'), name='unique_name_event_type'),
        ),
        migrations.AddConstraint(
            model_name='resourceconsumption',
            constraint=models.UniqueConstraint(fields=('resource_type', 'ticket_type'), name='unique_resource_type_ticket_type'),
        ),
    ]
