# Generated by Django 5.2 on 2025-05-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpacabooking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
    ]
