# Generated by Django 5.2 on 2025-05-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpacabooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
                ('teaser', models.TextField(blank=True)),
                ('sponsorshipAvailable', models.BooleanField(default=False)),
                ('hasCurrentSponsorship', models.BooleanField(default=False)),
                ('sponsorName', models.CharField(blank=True, max_length=128)),
                ('sponsorCustomText', models.TextField(blank=True)),
            ],
        ),
    ]
